# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: AssembyInfoReader@3
  inputs:
    searchPattern: 'JANL\My Project\AssemblyInfo.vb'

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: 'Write-Host "##vso[task.setvariable variable=name;]$(AssemblyInfo.AssemblyVersion)"'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Version: $(AssemblyInfo.AssemblyVersion)"
      Write-Host "##vso[build.updatebuildnumber]$(AssemblyInfo.AssemblyVersion)-$(rev:r)"

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(AssemblyInfo.AssemblyVersion)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'