name: Build artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    outputs:
      version: 
        description: "Version builded"
        value: ${{ jobs.build.outputs.version }}
        
jobs:
  build:
    name: Build
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      SolutionName: JANL.sln
      Configuration: ${{ matrix.configuration }}
      
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Set VERSION
      id: version
      run: |
        dotnet tool install -g minver-cli --version 2.5.0
        $version = minver -t v -d preview
        $number = $version.Split('-')[0]
        echo "VERSION=$version"
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "::set-output name=version::$version"
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore solution
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration
        
    - name: Build solution
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration

    - name: Pack NuGet
      run: nuget pack .\JANL\JANL.nuspec -Version ${{ env.VERSION }}
      
    - name: Upload artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
        name: JANL
        path: '**\*.nupkg'
        if-no-files-found: error
